create table public.basil_social_digests (
  id uuid primary key default gen_random_uuid(),
  run_key text not null unique,
  status text not null default 'review_ready',
  reviewer_emails jsonb not null default '[]'::jsonb,
  approval_token_hash text not null unique,
  approval_expires_at timestamptz not null,
  source_snapshot jsonb not null default '{}'::jsonb,
  review_email_id text,
  review_email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint basil_social_digest_run_key_length
    check (char_length(run_key) between 8 and 40),
  constraint basil_social_digest_status_check
    check (status in ('review_ready', 'in_review', 'completed', 'archived', 'failed')),
  constraint basil_social_digest_reviewers_array
    check (jsonb_typeof(reviewer_emails) = 'array'),
  constraint basil_social_digest_source_object
    check (jsonb_typeof(source_snapshot) = 'object'),
  constraint basil_social_digest_token_hash
    check (approval_token_hash ~ '^[0-9a-f]{64}$')
);

create table public.basil_social_stories (
  id uuid primary key default gen_random_uuid(),
  digest_id uuid not null references public.basil_social_digests(id) on delete cascade,
  story_key text not null,
  source_type text not null,
  source_ref text,
  title text not null,
  summary text not null,
  why_today text not null,
  asset_url text not null,
  asset_kind text not null default 'image',
  evidence jsonb not null default '{}'::jsonb,
  rank integer not null,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (digest_id, story_key),
  unique (digest_id, rank),
  constraint basil_social_story_key_length check (char_length(story_key) between 1 and 80),
  constraint basil_social_story_source_check check (source_type in ('repository', 'garden_stats', 'evergreen', 'manual')),
  constraint basil_social_story_title_length check (char_length(title) between 1 and 180),
  constraint basil_social_story_summary_length check (char_length(summary) between 1 and 1200),
  constraint basil_social_story_why_length check (char_length(why_today) between 1 and 600),
  constraint basil_social_story_asset_length check (char_length(asset_url) between 1 and 2000),
  constraint basil_social_story_asset_kind check (asset_kind in ('image', 'video')),
  constraint basil_social_story_evidence_object check (jsonb_typeof(evidence) = 'object'),
  constraint basil_social_story_rank check (rank between 1 and 20),
  constraint basil_social_story_status check (status in ('draft', 'ready', 'held', 'archived'))
);

create table public.basil_social_variants (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references public.basil_social_stories(id) on delete cascade,
  channel text not null,
  headline text not null,
  body text not null,
  hashtags jsonb not null default '[]'::jsonb,
  status text not null default 'draft',
  approved_at timestamptz,
  published_at timestamptz,
  published_url text,
  external_id text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (story_id, channel),
  constraint basil_social_variant_channel check (channel in ('reddit', 'youtube', 'instagram', 'tiktok')),
  constraint basil_social_variant_headline_length check (char_length(headline) between 1 and 300),
  constraint basil_social_variant_body_length check (char_length(body) between 1 and 10000),
  constraint basil_social_variant_hashtags_array check (jsonb_typeof(hashtags) = 'array'),
  constraint basil_social_variant_status check (status in ('draft', 'manual_ready', 'rejected', 'published', 'failed')),
  constraint basil_social_variant_url_length check (published_url is null or char_length(published_url) between 1 and 2000),
  constraint basil_social_variant_external_id_length check (external_id is null or char_length(external_id) between 1 and 300),
  constraint basil_social_variant_error_length check (last_error is null or char_length(last_error) <= 1000)
);

create table public.basil_social_metrics (
  id bigint generated by default as identity primary key,
  variant_id uuid not null references public.basil_social_variants(id) on delete cascade,
  measured_at timestamptz not null default now(),
  window_key text not null,
  impressions bigint not null default 0,
  views bigint not null default 0,
  engaged_views bigint not null default 0,
  reactions bigint not null default 0,
  comments bigint not null default 0,
  shares bigint not null default 0,
  saves bigint not null default 0,
  clicks bigint not null default 0,
  tutorial_starts bigint not null default 0,
  memberships bigint not null default 0,
  watch_seconds numeric not null default 0,
  raw jsonb not null default '{}'::jsonb,
  unique (variant_id, window_key),
  constraint basil_social_metric_window_length check (char_length(window_key) between 1 and 40),
  constraint basil_social_metric_nonnegative check (
    impressions >= 0 and views >= 0 and engaged_views >= 0 and reactions >= 0
    and comments >= 0 and shares >= 0 and saves >= 0 and clicks >= 0
    and tutorial_starts >= 0 and memberships >= 0 and watch_seconds >= 0
  ),
  constraint basil_social_metric_raw_object check (jsonb_typeof(raw) = 'object')
);

create index basil_social_digests_status_created_idx
  on public.basil_social_digests (status, created_at desc);
create index basil_social_stories_digest_rank_idx
  on public.basil_social_stories (digest_id, rank);
create index basil_social_variants_status_updated_idx
  on public.basil_social_variants (status, updated_at desc);
create index basil_social_metrics_variant_measured_idx
  on public.basil_social_metrics (variant_id, measured_at desc);

alter table public.basil_social_digests enable row level security;
alter table public.basil_social_stories enable row level security;
alter table public.basil_social_variants enable row level security;
alter table public.basil_social_metrics enable row level security;

revoke all on table public.basil_social_digests from public, anon, authenticated;
revoke all on table public.basil_social_stories from public, anon, authenticated;
revoke all on table public.basil_social_variants from public, anon, authenticated;
revoke all on table public.basil_social_metrics from public, anon, authenticated;
grant select, insert, update, delete on table public.basil_social_digests to service_role;
grant select, insert, update, delete on table public.basil_social_stories to service_role;
grant select, insert, update, delete on table public.basil_social_variants to service_role;
grant select, insert, update, delete on table public.basil_social_metrics to service_role;
grant usage, select on sequence public.basil_social_metrics_id_seq to service_role;

comment on table public.basil_social_digests is
  'Private approval-first Basil Social Studio digest runs. Only token hashes are stored.';
comment on table public.basil_social_stories is
  'Private evidence-backed social story candidates and their approved gameplay assets.';
comment on table public.basil_social_variants is
  'Editable, channel-specific copy with explicit manual approval and publication state.';
comment on table public.basil_social_metrics is
  'Normalized performance snapshots for published Basil social variants.';

create or replace function public.get_basil_social_stats()
returns jsonb
language sql
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'measuredAt', now(),
    'communityFlowers', (select count(*) from public.community_garden_roses),
    'roses', (select count(*) from public.community_garden_roses where plant_type = 'rose'),
    'sunflowers', (select count(*) from public.community_garden_roses where plant_type = 'sunflower'),
    'lavender', (select count(*) from public.community_garden_roses where plant_type = 'lavender'),
    'weeds', (select count(*) from public.community_garden_weeds),
    'gardenMembers', (
      select count(distinct steward_id)
      from public.garden_entitlements
      where status = 'active'
    ),
    'personalGardenFlowers', (select count(*) from public.garden_personal_plants),
    'livingGardenDiscoveries', (select count(*) from public.my_garden_habitat_discoveries),
    'careSharedThisMonth', (
      select coalesce(sum(greatest(care_delta, 0)), 0)
      from public.garden_care_ledger
      where created_at >= date_trunc('month', now())
    )
  );
$$;

revoke all on function public.get_basil_social_stats() from public, anon, authenticated;
grant execute on function public.get_basil_social_stats() to service_role;

comment on function public.get_basil_social_stats() is
  'Returns aggregate, non-identifying garden statistics for private Social Studio draft generation.';
