create table public.basil_agent_care_ledger (
  id bigint generated by default as identity primary key,
  agent_id uuid not null references public.basil_agent_profiles(id) on delete cascade,
  steward_id uuid not null references public.garden_stewards(id) on delete cascade,
  budget_date date not null,
  amount smallint not null,
  reason text not null default 'daily_maintenance_budget',
  created_at timestamptz not null default now(),
  unique (agent_id, budget_date, reason),
  constraint basil_agent_care_amount_check check (amount between 0 and 8),
  constraint basil_agent_care_reason_check check (reason in ('daily_maintenance_budget', 'founding_grant', 'action_receipt'))
);

create index basil_agent_care_ledger_agent_date_idx
  on public.basil_agent_care_ledger (agent_id, budget_date desc);

alter table public.basil_agent_care_ledger enable row level security;
revoke all on table public.basil_agent_care_ledger from public, anon, authenticated;
grant select, insert, update, delete on table public.basil_agent_care_ledger to service_role;
grant usage, select on sequence public.basil_agent_care_ledger_id_seq to service_role;

create or replace function public.grant_basil_agent_daily_care(
  p_agent_code text,
  p_budget_date date,
  p_amount smallint default 6
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  resolved_agent public.basil_agent_profiles%rowtype;
  inserted_id bigint;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'Not authorized.' using errcode = '42501';
  end if;
  if p_amount < 0 or p_amount > 8 then
    raise exception 'Agent Care budget must be between zero and eight.' using errcode = '22023';
  end if;

  select * into resolved_agent
  from public.basil_agent_profiles
  where code = p_agent_code and enabled
  limit 1;
  if resolved_agent.id is null then
    raise exception 'Agent not found.' using errcode = 'P0002';
  end if;

  insert into public.basil_agent_care_ledger (
    agent_id,
    steward_id,
    budget_date,
    amount,
    reason
  ) values (
    resolved_agent.id,
    resolved_agent.garden_steward_id,
    p_budget_date,
    p_amount,
    'daily_maintenance_budget'
  )
  on conflict (agent_id, budget_date, reason) do nothing
  returning id into inserted_id;

  if inserted_id is null then
    return false;
  end if;

  update public.garden_member_progress
  set care_balance = care_balance + p_amount,
      updated_at = now()
  where steward_id = resolved_agent.garden_steward_id;

  return true;
end;
$$;

revoke all on function public.grant_basil_agent_daily_care(text, date, smallint)
  from public, anon, authenticated;
grant execute on function public.grant_basil_agent_daily_care(text, date, smallint)
  to service_role;

comment on table public.basil_agent_care_ledger is
  'Private, auditable non-player Care grants for system-agent My Gardens. Daily maintenance is capped at eight and does not increase lifetime player progression.';
comment on function public.grant_basil_agent_daily_care(text, date, smallint) is
  'Idempotently grants a capped system-agent maintenance budget. Service role only.';
